@echo off
rem One visit of a contrib/uniswap_v3 paper run, for Windows Task Scheduler
rem (paper-visit.xml runs it three times a day). It appends the visit's
rem output to a log file and exits with the visit's exit code: 0 done
rem (decided now, already decided, or the chain had no answer at the
rem boundary, which the log warns of), 1 something needs fixing, 3 try again
rem later. It exits 4 itself when it cannot get to the repository, cannot
rem write the log, or PYTHON names a path that is not there: the visit is not
rem run then. See contrib/uniswap_v3/RUNBOOK.md.
setlocal

rem The settings. To change one, do not edit this file: put its `set` line
rem in paper-visit.local.cmd beside it (gitignored), which is read next.
rem A relative path is taken from the repository root, where the visit runs.
set "RUN_ID=paper-1"
set "CONFIG=%~dp0..\configs\paper.local.yaml"
set "DB=%~dp0..\data\paper.db"
set "LOG=%~dp0..\data\paper-visits.log"
rem The python.exe that has contrib/uniswap_v3/requirements.txt installed (an
rem .exe: a .cmd or .bat shim would not hand control back to this script).
rem The task runs with your PATH.
set "PYTHON=python"
if exist "%~dp0paper-visit.local.cmd" call "%~dp0paper-visit.local.cmd"

rem What the visit prints reaches the log as it is printed, so a visit the
rem task stops still leaves its lines behind.
set "PYTHONUNBUFFERED=1"
rem The repository root, where the .env file with ETH_RPC_URL is.
cd /d "%~dp0..\..\.." || exit /b 4
for %%F in ("%LOG%") do if not exist "%%~dpF" mkdir "%%~dpF"
rem A log that cannot be written would hide whatever the visit did: stop.
rem Settings are echoed in quotes: a path may hold an & or a parenthesis.
>>"%LOG%" echo ==== %DATE% %TIME% visit of "%RUN_ID%" (db "%DB%", python "%PYTHON%") || exit /b 4
rem A PYTHON given as a path that is not there: cmd would exit 3 for a missing
rem directory, which reads as "try again later". It is a setting to fix.
if not "%PYTHON:\=%"=="%PYTHON%" if not exist "%PYTHON%" (
    >>"%LOG%" echo ==== there is no "%PYTHON%": fix PYTHON in paper-visit.local.cmd
    >>"%LOG%" echo ==== exit 4
    exit /b 4
)
rem No --balance or --gas-eth: the run is started by hand once (RUNBOOK.md).
rem A visit to a run that is not there then fails with exit 1 instead of
rem quietly starting a new run under a mistyped --db or --run-id.
"%PYTHON%" -m dotenv run -- "%PYTHON%" -m contrib.uniswap_v3 paper --config "%CONFIG%" --db "%DB%" --run-id "%RUN_ID%" >>"%LOG%" 2>&1
set "CODE=%ERRORLEVEL%"
>>"%LOG%" echo ==== exit %CODE%
exit /b %CODE%
