#!/bin/sh
# One visit of the contrib/uniswap_v3 paper runs, for a systemd timer
# (uniswap-v3-paper.timer runs it three times a day) or any other scheduler.
# It appends every command's output to a log file and exits with the first
# exit code that is not 0: 0 done (decided now, already decided, or the chain
# had no answer at the boundary, which the log warns of), 1 something needs
# fixing, 3 try again later. It exits 4 itself when it cannot get to the
# repository or write the log, or PYTHON names a path that is not there: the
# visit is not run then; and when the log stops taking writes mid-visit: the
# steps before ran, the rest do not. See contrib/uniswap_v3/RUNBOOK.md.
#
# A visit is, in this order, and each step only when the one before exited 0:
#   1. paper     the control run, which reads no verdicts;
#   2. backfill  today's bar into the store (the verdict command reads the
#                store alone, and the AI run's paper decides as it reads);
#   3. verdict   the judge's verdict on every traded token at that bar;
#   4. paper     the AI-gated run, which reads the verdicts.
# A retry does not ask again for a verdict that was already given: the
# command keeps what it has and asks only about the rest. An empty RUN_TREND
# leaves out step 1, an empty RUN_AI steps 2 to 4, each said in the log; both
# empty is a setting to fix, exit 1.
set -u

# The settings. To change one, do not edit this file: put its line in
# paper-visit.local.sh beside it (gitignored), which is read next, as
# NAME="value", one per line, nothing else (the file is sourced). A relative
# path is taken from the repository root, where the visit runs.
RUN_TREND=paper-trend-1
RUN_AI=paper-ai-1
CONFIG_TREND=contrib/uniswap_v3/configs/paper-trend.local.yaml
CONFIG_AI=contrib/uniswap_v3/configs/paper-ai.local.yaml
DB=contrib/uniswap_v3/data/paper.db
LOG=contrib/uniswap_v3/data/paper-visits.log
# The python that has the engine and contrib/uniswap_v3/requirements.txt
# installed: a venv's bin/python, as a rule.
PYTHON=python3
here=$(cd "$(dirname "$0")" && pwd) || exit 4
if [ -f "$here/paper-visit.local.sh" ]; then . "$here/paper-visit.local.sh"; fi

# What a command prints reaches the log as it is printed, so a visit the
# scheduler stops still leaves its lines behind.
export PYTHONUNBUFFERED=1
# The repository root, where the .env file with ETH_RPC_URL and the key is.
cd "$here/../../.." || exit 4
mkdir -p "$(dirname "$LOG")" 2>/dev/null
# A log that cannot be written would hide whatever the visit did: stop.
echo "==== $(date -u +%Y-%m-%dT%H:%M:%SZ) visit of \"$RUN_TREND\" and \"$RUN_AI\" (db \"$DB\", python \"$PYTHON\")" >>"$LOG" 2>/dev/null || exit 4
say() {
    echo "==== $*" >>"$LOG"
}
finish() {
    say "exit $1"
    exit "$1"
}
# A PYTHON given as a path that is not there is a setting to fix, not a
# "try again later".
case "$PYTHON" in
*/*)
    if [ ! -x "$PYTHON" ]; then
        say "there is no \"$PYTHON\": fix PYTHON in paper-visit.local.sh"
        finish 4
    fi
    ;;
esac

# No --balance or --gas-eth: a run is started by hand once (RUNBOOK.md). A
# visit to a run that is not there then fails with exit 1 instead of quietly
# starting a new run under a mistyped DB or run id.
run() {
    # A log that stopped taking writes mid-visit would turn into a redirect
    # failure, exit 2 under dash, which reads as a mistyped command: it is 4.
    [ -w "$LOG" ] || exit 4
    "$PYTHON" -m dotenv run -- "$PYTHON" -m contrib.uniswap_v3 "$@" >>"$LOG" 2>&1
}

if [ -z "$RUN_TREND" ] && [ -z "$RUN_AI" ]; then
    say "RUN_TREND and RUN_AI are both empty: nothing to visit; fix paper-visit.local.sh"
    finish 1
fi
if [ -n "$RUN_TREND" ]; then
    run paper --config "$CONFIG_TREND" --db "$DB" --run-id "$RUN_TREND" || finish $?
else
    say "RUN_TREND is empty: the control run is left out"
fi
if [ -n "$RUN_AI" ]; then
    run backfill --config "$CONFIG_AI" --db "$DB" --from "$(date -u +%Y-%m-%d)" || finish $?
    run verdict --config "$CONFIG_AI" --db "$DB" || finish $?
    run paper --config "$CONFIG_AI" --db "$DB" --run-id "$RUN_AI" || finish $?
else
    say "RUN_AI is empty: backfill, verdict and the AI run are left out"
fi
finish 0
